title: Ryker Kolllmyer
logo: /assets/img/sadasdasd.png
description: Drones · Multi-Agent Systems · AI · Planes
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
sass:
  sass_dir: assets/css
